[package]
name = "sequencer"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
# Starknet
# TODO: remove the blockifier patch on the workspace once we can remove Katana.
blockifier = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
starknet_api = { workspace = true }
starknet = { workspace = true }

# Other
eyre = { workspace = true }
tracing = { workspace = true }
rustc-hash = "1.1.0"
thiserror = { workspace = true }

[dev-dependencies]
lazy_static = { workspace = true }
tempfile = "3.8.0"
