[package]
name = "sequencer"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Starknet
blockifier = { git = "https://github.com/starkware-libs/blockifier.git", tag = "v0.3.0-rc0" }
starknet_api = "0.5.0-rc1"
starknet = { workspace = true }

# Other
rustc-hash = "1.1.0"

[dev-dependencies]
lazy_static = { workspace = true }
