[package]
name = "ef-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bytes = { workspace = true }

# Eth deps
ef-tests = { workspace = true }
ethers-signers = { workspace = true }
reth-primitives = { workspace = true }
revm-primitives = { workspace = true }
reth-rlp = { workspace = true }

# Kakarot deps
sequencer = { path = "../sequencer" }

# Starknet deps
blockifier = { workspace = true }
cairo-vm = { workspace = true }
starknet_api = { workspace = true }
starknet = { workspace = true }

# Log
log = { workspace = true }

# Other
async-trait = { workspace = true }
ctor = { workspace = true }
chrono = { workspace = true, optional = true }
dotenvy = { workspace = true, optional = true }
eyre = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true, optional = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
ef-testing-proc-macros = { path = "../ef-testing-proc-macros" }
